name: Windows-arm64
on: 
  workflow_dispatch:
  push:
jobs:
  build:
    name: Build
    # see https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        qt_ver: [6.4.3]
        qt_arch: [win64_msvc2019_arm64]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'         
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          modules: qtwebengine qtwebchannel qtpositioning qt5compat qtmultimedia qtimageformats qtspeech
          setup-python: 'false'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64_arm64   
      - name: msvc-build goldendict
        id: build
        shell: cmd
        run: |
          qmake "CONFIG+=zim_support" CONFIG+=release CONFIG+=use_iconv CONFIG+=use_xapian
          nmake
